### ISSUE TITLE
Determine naming convention for all components

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/summit2016-ose-cicd#7]
Determine the final naming solutions for the following components:
- UI Application
- Base Images
- Jenkins Jobs
  - Base Image trigger
  - Base Image
  - App Image trigger
  - App
- OpenShift project names
  *Remove the use of the word "swarm"

**Comment by sabre1041** [comment]
Proposed names
- Base S2I Image
  - Repository
    - base-image
  - Jenkins
    - base-image-pipeline
    - base-image-is-trigger
  - OpenShift Project
    - base-image
- OSE UI Application
  - Repository
    - ose-api-app
  - Jenkins
    - ose-api-app-pipeline
    - ose-api-app-is-trigger
  - OpenShift Project
    - api-app-dev
    - api-app-prod

@JaredBurck what do you think?

**Comment by JaredBurck** [comment]
I think those names are good.  Questions about base, since we talk about that in our preso.  Do you think base-image will make people think rhel/centos type of base?  Or do you think people will understand base-image as our starting point.   Other than that, I like these a lot!!!

@sabre1041 Your thoughts?

**Comment by sabre1041** [comment]
As per discussion with @JaredBurck we wll use `custom-base-image`

Finalized names:
- Base S2I Image
  - Repository
    - custom-base-image
  - Jenkins
    - custom-base-image-pipeline
    - custom-base-image-is-trigger
  - OpenShift Project
    - custom-base-image
- OSE UI Application
  - Repository
    - ose-api-app
  - Jenkins
    - ose-api-app-pipeline
    - ose-api-app-is-trigger
  - OpenShift Project
    - api-app-dev
    - api-app-prod

**Comment by sabre1041** [comment]
Has been determined and implemented
